export default {
  root: 'w-full',
  item: 'transition-colors not-last:border-b',
  trigger: [
    'w-full',
    'flex',
    'justify-between',
    'items-center',
    'gap-2',
    'py-4',
    'text-sm',
    'rounded-shape',
    'transition-colors',
    'hover:underline',
    'focusable',
    'focus-visible:outline-outline',
    '[&[data-open=true]>svg]:-rotate-180',
  ].join(' '),
  arrow: 'size-4 transition-transform shrink-0',
  content: 'pt-0 pb-4',
};
